### ISSUE TITLE
`Vector#head` and `Vector#tail` not returning correct value

### ISSUE THREAD

**Issue by ruivieira** [ruivieira/crystal-gsl#16]
```crystal
v = GSL::Vector.new [1.0, 2.0, 3.0]
v.tail
```

returns

`gsl: ../gsl/gsl_vector_double.h:180: ERROR: index out of range`.

The vector's size seems to be hardcoded (`5`).

@dylandy This from commit eba6af51c85a3ecb8d495de2405504a7c050e123, is it possible to have a look. A spec test for `tail` and `head` would be great too. Thanks!

**Comment by dylandy** [comment]
fixed in pull request #17
