### ISSUE TITLE
Any chance the rest of the GSL would be implemented?

### ISSUE THREAD

**Issue by u89012** [ruivieira/crystal-gsl#25]

**Comment by ruivieira** [comment]
Yes, definitely.
Unfortunately I can't make any commitment as to when, since this is a spare time project and GSL itself is quite big.
Contributions are always welcome :)

**Comment by u89012** [comment]
Yes indeed! I'm a Crystal noob but I'll see what I can do! Thanks for all your hard work!

**Comment by ruivieira** [comment]
I'll close this issue, start a FAQ on the README.md and include this question.
