### ISSUE TITLE
Consider changing license to GPL

### ISSUE THREAD

**Issue by konovod** [ruivieira/crystal-gsl#33]
GSL itself is distributed under GPL (https://www.gnu.org/software/gsl/ section Licensing), so any code that uses it will be under GPL. 
So while it is technically possible to have this wrapper under MIT (as it's compatible with GPL) I don't see much point in it.

**Comment by ruivieira** [comment]
Hi @konovod, I agree, especially with the inclusion of https://github.com/ruivieira/crystal-gsl/pull/32. Thanks.
