### ISSUE TITLE
Proposals for file layout

### ISSUE THREAD

**Issue by ruivieira** [ruivieira/crystal-gsl#9]
At the moment the file layout is the following:

```
.
|____gsl
| |____base
| | |____error.cr
| | |____iterator.cr
| | |____libgsl.cr
| | |____matrices.cr
| | |____statistics.cr
| | |____validator.cr
| | |____vector.cr
| |____maths
| | |____basic
| | | |____sorting.cr
| | | |____vector.cr
| | |____statistics
| | | |____vector.cr
| |____version.cr
|____gsl.cr
```

Two obvious candidates for the current code are `statistics` and merging `vector.cr` and `matrices.cr` into something like `linalg`.

Also, `Vector` and `Matrix` are in the `Statistics` namespace which should be changed.

**Comment by dylandy** [comment]
I think that for vector and matrix class, we can just follow the original GSL namespace like ```GSL::Vector``` and  ```GSL::Matrix```.

**Comment by dylandy** [comment]
I don't know if it is a better idea to organise naming like [rb-gsl](https://github.com/SciRuby/rb-gsl)

**Comment by ruivieira** [comment]
Yes, I agree that `GSL::*` is a good starting point for a namespace.
